 const categoriesData = {
    
    Accommodation: [
      "Hotels",
      "Resorts",
      "Motels",
      "Bed & Breakfast",
      "air bnb",
      "Inns",
      "Guest Houses",
      "Vacation Villas",
      "Camping Sites",
      "Glamping Sites",
      "Time Shares",
    ],
    Dining: [
      "Traditional foods",
      "Restaurants",
      "Cafes & Coffee Shops",
      "Bakeries",
      "Bars & Pubs",
      "Food Trucks",
      "Fine Dining Restaurants",
      "Ethnic Cuisine Restaurants",
      "Fast Food Chains",
      "Sea food",
    ],
    Entertainment: [
      "Cinema & Theaters",
      "Music & Live Performances",
      "Nightlife",
      "Gaming & Indoor Fun",
      "Amusement & Recreation",
      "Sports & Outdoor Activities",
    ],
    Culture_and_Historicalsites: [
      "Museums",
      "Art Galleries",
      "Historic Landmarks",
      "Monuments",
      "Archaelogical Sites",
      "Cultural Sites",
      "Heritage Sites",
      "Religious places of interest",
    ],
    Shopping: [
      "Shopping Malls",
      "Boutiques",
      "Markets",
      "Antique Stores",
      "Souvenir Shops",
      "Department stores",
      "Outlet Stores",
      "Speciality Stores",
    ],
    Education_and_Learning: [
      "Libraries",
      "Bookstores",
      "Education Centers",
      "Art Schools",
      "Cooking Schools",
      "Language Schools",
      "Workshops & Classes",
      "Research Institution",
    ],
    
    Services: [
      "Spar & massage centers",
      "Hair Salons",
      "Nail Salons",
      "Dry Cleaners",
      "Pet Groomers",
      "Gym",
      "Car Washes",
      "Post Offices",
      "Banks and atm's",
      "legal Services",
      "Swimming Pools",
      "Martial arts Studios",
      "Dance Studio",
      "Hospital",
    ],
  };

  export default categoriesData;